### ISSUE TITLE
CancellationToken as optional Argument for Async functions.

### ISSUE THREAD

**Issue by Feroks** [VaudoiseAssurances/MediatR.EventAggregator#3]
PublishAsync and SubscribeAsync cannot be canceled. I am not sure someone is going to cancel these methods, but having it as an option is always nice.

**Comment by salfab** [comment]
Wow, thank you very much for your review, stranger :)

![](https://i.giphy.com/media/g9582DNuQppxC/giphy.webp)

I added a Pull request (https://github.com/VaudoiseAssurances/MediatR.EventAggregator/pull/5) to fix this.
